# Generated by Django 3.2.9 on 2021-11-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_mat', '0002_auto_20211125_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='perfil_mat.materia'),
        ),
    ]
