# Generated by Django 3.2.9 on 2021-11-28 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_mat', '0003_alter_comentario_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='perfil_mat.materia'),
        ),
    ]
